server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kinoteca
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/databasechangelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: KinotecaParser
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
kinopoisk-api:
  key: 6MFSRQG-576MHNX-QXX7F9K-HD4ZJ31
  base-url: https://api.kinopoisk.dev/documentation
application:
  base-url: /info/movies

